### ISSUE TITLE
UnicodeDecodeError with python 3.4.2

### ISSUE THREAD

**Issue by edvm** [geex-arts/django-jet#11]
When running pip install django-jet with python 3.4.2 i got the following error:
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2496: ordinal not in range(128)```

Complete traceback is:

```
  Downloading django-jet-0.1.0.tar.gz (734kB): 734kB downloaded
  Running setup.py (path:/tmp/pip-build-s6sd7ah1/django-jet/setup.py) egg_info for package django-jet
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-s6sd7ah1/django-jet/setup.py", line 21, in <module>
        long_description=read('README.rst'),
      File "/tmp/pip-build-s6sd7ah1/django-jet/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/home/edvm/.virtualenvs/inmobiz/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2496: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-s6sd7ah1/django-jet/setup.py", line 21, in <module>

    long_description=read('README.rst'),

  File "/tmp/pip-build-s6sd7ah1/django-jet/setup.py", line 6, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

  File "/home/edvm/.virtualenvs/inmobiz/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2496: ordinal not in range(128)
```

**Comment by f1nality** [comment]
Fixed in 0.1.1. Thank you!
