### ISSUE TITLE
Google analytics fails to fetch data

### ISSUE THREAD

**Issue by rakanalh** [geex-arts/django-jet#133]
Hello,

There's a problem with Google Analytics widgets. I've setup them with the proper access, and they start showing data normally. 
Once i navigate to a different page and return back to the dashboard homepage, the widgets show errors:

![example](http://i.imgur.com/Rfhx3oOl.png)

What could be the issue?

**Comment by rakanalh** [comment]
I've printed the traceback of the issue:
```
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/jet/dashboard/dashboard_modules/google_analytics.py", line 293,in api_ga
    result, exception = client.api_ga(self.counter, date1, date2, group)
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/jet/dashboard/dashboard_modules/google_analytics.py", line 131,in api_ga
    dimensions=dimensions
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/googleapiclient/http.py", line 833, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/googleapiclient/http.py", line 160, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/oauth2client/transport.py", line 180, in new_request
    credentials._refresh(orig_request_method)
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/oauth2client/client.py", line 767, in _refresh
    self.store.acquire_lock()
  File "/home/vagrant/.pyenv/versions/Proj/lib/python2.7/site-packages/oauth2client/client.py", line 360, in acquire_lock
    if self._lock is not None:
AttributeError: 'ModuleCredentialStorage' object has no attribute '_lock'
```

**Comment by SalahAdDin** [comment]
Could be a incompatibility with the latest google client python library. @f1nality

**Comment by f1nality** [comment]
@SalahAdDin yes, most likely

@rakanalh which version of google-api-python-client are you using? I've been using google-api-python-client (1.4.1) and it works. Please try ``pip install google-api-python-client==1.4.1``. If it helps, than documentation should be updated with the particular package version.

**Comment by rakanalh** [comment]
Tried version 1.4.1 and it works as stated.

Thanks

**Comment by SalahAdDin** [comment]
@f1nality But, won't be better update `django-jet` for works with lastest `google-api-python-client`.

**Comment by f1nality** [comment]
@SalahAdDin has it any benefits? I don't any issues with 1.4.1

**Comment by rakanalh** [comment]
@f1nality i guess unless the dependency is hardcoded into jet's setup.py, other people might have the same issue.

**Comment by ebergmundur** [comment]
google-api-python-client==1.4.1 requires oauth2client==3.0 4.0 will fail complaining about utils.

**Comment by SalahAdDin** [comment]
@f1nality What's about solve this bug?
