### ISSUE TITLE
Django jet seem is deleting my session data

### ISSUE THREAD

**Issue by mayela** [geex-arts/django-jet#152]
I have to change on ModelAdmin's get_queryset when I'm in list of all models the qet_queryset works well

![captura de pantalla de 2016-11-28 10-59-24](https://cloud.githubusercontent.com/assets/665952/20677734/c1db6eac-b559-11e6-9971-1c721c255ebc.png)

but when I go to the detail view of the unique object showed I got an error

![captura de pantalla de 2016-11-28 11-01-28](https://cloud.githubusercontent.com/assets/665952/20677816/0c60adde-b55a-11e6-8127-97cca9f3056f.png)

`    def get_queryset(self, request):
        session_user = User.objects.filter(username=request.session['session_username'])
        qs = super(DocumentAdmin, self).get_queryset(request)
        return qs.filter(responsible=session_user)
`
`
Internal Server Error: /admin/tasks/tasks/1312/change/
Traceback (most recent call last):
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 392, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/jet/templatetags/jet_tags.py", line 253, in jet_previous_object_url
    return jet_sibling_object_url(context, False)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/jet/templatetags/jet_tags.py", line 223, in jet_sibling_object_url
    queryset = get_model_queryset(admin_site, model, preserved_filters=preserved_filters)
  File "/home/maricela/Documentos/nyx_projects/alessa/venv/local/lib/python2.7/site-packages/jet/utils.py", line 186, in get_model_queryset
    queryset = model_admin.get_queryset(request)
  File "/home/maricela/Documentos/nyx_projects/alessa/apps/tasks/admin.py", line 152, in get_queryset
    session_user = User.objects.filter(username=request.session['session_username'])
AttributeError: 'WSGIRequest' object has no attribute 'session'
[28/Nov/2016 11:00:46] "GET /admin/tasks/tasks/1312/change/ HTTP/1.1" 500 414660
`

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄
