### ISSUE TITLE
Google analytics is not working

### ISSUE THREAD

**Issue by pwndr00t** [geex-arts/django-jet#160]
I have double checked everything and they all seems fine.
However, I have this error on starting server.
Why it cannot find util from oauth2client?

```
python.exe .\manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x03777030>
Traceback (most recent call last):
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\creep\Code\Python\test\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\creep\Code\Python\test\test\test\urls.py", line 1, in <module>
    from jet.dashboard.dashboard_modules import google_analytics_views
  File "C:\Users\creep\Code\Python\test\lib\site-packages\jet\dashboard\dashboard_modules\google_analytics_views.py", line 6, in <module>
    from jet.dashboard.dashboard_modules.google_analytics import GoogleAnalyticsClient, ModuleCredentialStorage
  File "C:\Users\creep\Code\Python\test\lib\site-packages\jet\dashboard\dashboard_modules\google_analytics.py", line 11, in <module>
    from googleapiclient.discovery import build
  File "C:\Users\creep\Code\Python\test\lib\site-packages\googleapiclient\discovery.py", line 53, in <module>
    from googleapiclient.errors import HttpError
  File "C:\Users\creep\Code\Python\test\lib\site-packages\googleapiclient\errors.py", line 26, in <module>
    from oauth2client import util
ImportError: cannot import name util```

**Comment by rcotrina94** [comment]
I solved this by installing `google-api-python-client` with `pip install google-api-python-client==1.4.1`.
The reason is explained by issue #133.

**Comment by rcotrina94** [comment]
I've discovered that upgrading `google-api-python-client` will cause another problem: referenced in the same issue #133

**Comment by SalahAdDin** [comment]
@f1nality What's about solve this bug?

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄
