### ISSUE TITLE
No module named 'jetdjango'

### ISSUE THREAD

**Issue by Gaara631** [geex-arts/django-jet#263]
Can't start server, makemigrations or do anything with django-jet. When removing jet from installed apps project runs
Recreating venv did not help.
What can i do with it?

Python version: 3.6.2
Django version 1.11.7
django-jet version 1.0.6

**TEMPLATES:**
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```
**INSTALLED_APPS:**
```
INSTALLED_APPS = [
    'jet'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userprofile',
    'ideas',
]
```
**pip freeze:**
```
Django==1.11.7
django-jet==1.0.6
djangorestframework==3.7.3
mysqlclient==1.3.12
pkg-resources==0.0.0
pytz==2017.3
```
**Traceback:**
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7faf88aec598>
Traceback (most recent call last):
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/home/gaara/PycharmProjects/IdeaSpot/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jetdjango'
```

**Comment by SalahAdDin** [comment]
I can understand why are asking for `jetdjango`.

**Comment by valych** [comment]
You are missing the comma after `jet` in `INSTALLED_APPS`

**Comment by SalahAdDin** [comment]
Yes, @valych, you are right!

**Comment by ulrichgero** [comment]
Hi! I'm facing the same problem. Any help?

**Comment by Suaz** [comment]
same problem here
any solutions?
