### ISSUE TITLE
Value Error when trying to access Admin Panel

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [geex-arts/django-jet#281]
Hello dear friends,

I recently decided to install Django-Jet, now that it is available with Django 2.0, I really tried it today.

However, whenever I try to access the admin panel, I obtain the following error:

![image](https://user-images.githubusercontent.com/10923599/34615848-7f009cea-f236-11e7-9cb4-acd2c316ecee.png)

Any advice on how to solve this ?

Thanks a lot,

Jonathan D.

**Comment by yeltsinseal** [comment]
Same here.

Console error:

```
[08/Jan/2018 03:38:24] "GET / HTTP/1.1" 200 16559
[08/Jan/2018 03:38:26] "GET / HTTP/1.1" 200 16559
[08/Jan/2018 03:38:26] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[08/Jan/2018 03:38:29] "GET /admin HTTP/1.1" 301 0
[08/Jan/2018 03:38:29] "GET /admin/ HTTP/1.1" 302 0
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\utils.py", line 64, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\loader.py", line 38, in select_template
    engines = _engine_list(using)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\utils.py", line 88, in all
    return [self[alias] for alias in self]
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\utils.py", line 88, in <listcomp>
    return [self[alias] for alias in self]
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\utils.py", line 79, in __getitem__
    engine = engine_cls(params)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Program Files (x86)\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\jet\templatetags\jet_tags.py", line 44, in <module>
    @register.assignment_tag(takes_context=True)
AttributeError: 'Library' object has no attribute 'assignment_tag'
[08/Jan/2018 03:38:29] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 153235
```

**Comment by DEKHTIARJonathan** [comment]
it doesn't seem to be the same error @yeltsinseal
