### ISSUE TITLE
error on autocomplete when using unmanaged model

### ISSUE THREAD

**Issue by vanyakosmos** [geex-arts/django-jet#437]
```
backend_1  | 2020-02-25 16:36:01 ERRO                django.request:222 > Internal Server Error: /jet/model_lookup/
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1  |     response = get_response(request)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 126, in _get_response
backend_1  |     response = self.process_exception_by_middleware(e, request)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 124, in _get_response
backend_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
backend_1  |     return func(request, *args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.8/site-packages/jet/views.py", line 63, in model_lookup_view
backend_1  |     if form.is_valid():
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 185, in is_valid
backend_1  |     return self.is_bound and not self.errors
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 180, in errors
backend_1  |     self.full_clean()
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 382, in full_clean
backend_1  |     self._clean_form()
backend_1  |   File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 409, in _clean_form
backend_1  |     cleaned_data = self.clean()
backend_1  |   File "/usr/local/lib/python3.8/site-packages/jet/forms.py", line 123, in clean
backend_1  |     if not self.request.user.has_perm('{}.{}'.format(data['app_label'], permission.codename)):
backend_1  | AttributeError: 'NoneType' object has no attribute 'codename'
```

**Comment by vanyakosmos** [comment]
Fixed by manually creating `change_` permissions for each un-managed model.
