### ISSUE TITLE
Bug with `jet_custom_dashboard` command with a custrom User model.

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#83]
In my  current project i have a custom User model and i try to test these command, i have then this bug:

```bash
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python3.5/site-packages/jet/management/commands/jet_custom_apps_example.py", line 25, in handle_noargs
    'user': None
  File "/usr/local/lib/python3.5/site-packages/jet/utils.py", line 56, in get_app_list
    perms = model_admin.get_model_perms(request)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py", line 586, in get_model_perms
    'add': self.has_add_permission(request),
  File "/code/user/admin.py", line 137, in has_add_permission
    return request.user.is_superuser
AttributeError: 'User' object has no attribute 'is_superuser'

```

How can solve it?

**Comment by f1nality** [comment]
Yes, it's a bug. Fixed in 0.9.1.
