### ISSUE TITLE
Duplicate app label name with django-oscar dashboard

### ISSUE THREAD

**Issue by SalahAdDin** [geex-arts/django-jet#90]
Ok, i foun this error installing `django-oscar` and `django-jet` in same project.

``` bash
./manage.py runserver                                                                                                 ✓  1567  11:22:45 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7febb8eafd90>
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: dashboard
```

I solved this and i'll make pr for it.

**Comment by contactr2m** [comment]
Thank you for this great project, 
Any update on this #90 issue?? I see merge #91 did not go well. Dashboard is really very common name. Explicit name would be good. I have done modification at project level but it would be good to have this in master branch.. 

Keep up the great work. 
cheers

**Comment by SalahAdDin** [comment]
@f1nality Many release versions and this bug still present:
```bash
./manage.py runserver                                                                                     ✓  886  15:12:22 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fae6a8190d0>
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/E-Commerce/base/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: dashboard
```
```
Quit the server with CONTROL-C.
edx.devstack.lms | Traceback (most recent call last):
edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/manage.py", line 112, in <module>
edx.devstack.lms |     startup.run()
edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/startup.py", line 51, in run
edx.devstack.lms |     django.setup()
edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
edx.devstack.lms |     apps.populate(settings.INSTALLED_APPS)
edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
edx.devstack.lms |     "duplicates: %s" % app_config.label)
edx.devstack.lms | django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: dashboard
edx.devstack.lms | Traceback (most recent call last):
edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/manage.py", line 112, in <module>
edx.devstack.lms |     startup.run()
edx.devstack.lms |   File "/edx/app/edxapp/edx-platform/lms/startup.py", line 51, in run
edx.devstack.lms |     django.setup()
edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
edx.devstack.lms |     apps.populate(settings.INSTALLED_APPS)
edx.devstack.lms |   File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
edx.devstack.lms |     "duplicates: %s" % app_config.label)
edx.devstack.lms | django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: dashboard
```

**Comment by Ismael-VC** [comment]
Please come to the django-jet Discord server so we can organize if you like:

  *   https://discord.gg/3yr5yeH

Welcome! 😄

**Comment by SalahAdDin** [comment]
It's solved in my fork.

**Comment by SalahAdDin** [comment]
I made a PR but... @f1nality

**Comment by solvire** [comment]
Would be nice to have this one fixed. Should be easy enough given there is an open PR on it.

**Comment by SalahAdDin** [comment]
I think there is more than one PR but @f1nality does not merge it.

**Comment by solvire** [comment]
It should be a fairly simple fix...  In my app I renamed my dashboard using something similar to what you did in your PR. Thanks for that. 

If he sees this thread - I purchased a commercial license if that helps with motivation. :)

**Comment by SalahAdDin** [comment]
@solvire I did the PR, yes, but @f1nality did never merge it.
